### ISSUE TITLE
[REQUEST] WebGL platform support

### ISSUE THREAD

**Issue by karasusan** [Unity-Technologies/com.unity.webrtc#470]
# Precondition

WebGL support has been advanced by external developers in Unity community.
Very thanks @nvanofwegen and @gtk2k
https://github.com/The-Barn-Games/com.unity.webrtc/tree/feature/webgl-support

WebGL support is a long journey and we have many issues with merging it to the main branch. So I made the feature branch that receiving contributions from developers.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/experimental/webgl-platform

# TODO

- [ ] Create a new branch that developing for WebGL platform (@karasusan)
- [ ] Set up CI process of the WebGL platform in the internal CI platform ((@karasusan)
- [ ] Create a first PR to the feature branch (@nvanofwegen)
- [ ] Pull Request review (@karasusan, @kannan-xiao4)
- [ ] Manage GitHub issues (@karasusan)

**Comment by karasusan** [comment]
This is the first PR
https://github.com/Unity-Technologies/com.unity.webrtc/pull/478

**Comment by karasusan** [comment]
> Set up CI process of the WebGL platform in the internal CI platform ((@karasusan)

I tried this topic last week, however, I found this is needed more time than I expected.
So we test the package for WebGL platform manually.

**Comment by karasusan** [comment]
memo: WRS-158

**Comment by karasusan** [comment]
The pull request(#554) above was merged into this feature branch on our repository.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/experimental/webgl-platform

Please feel free to try WebGL build using this branch. And post issues on this thread if you find.

**Comment by karasusan** [comment]
The issue below is posted in Unity forum 
https://forum.unity.com/threads/webgl-platform-support.1147331/#post-7884949

**Comment by Thaina** [comment]
Is it possible to add support for microphone in browser too?

**Comment by karasusan** [comment]
@Thaina
I guess the `MediaStreamAddUserMedia` API is not supported for microphone.
Do you have any ideas? @nvanofwegen

**Comment by Thaina** [comment]
As far as I can see `MediaStreamAddUserMedia` was called `navigator.mediaDevices.getUserMedia` which seem totally about microphone so I wish it did work and I am started to try using it now. But because it has no sample I still try to figure out how to start with it

https://github.com/Unity-Technologies/com.unity.webrtc/blob/a39e89c2b18f37c093977ce3106f1305fd03992a/Runtime/Plugins/WebGL/MediaStream.jslib#L28-L37

**Comment by Thaina** [comment]
I has play with api and it seem I could open microphone and register stream and track. Only these function was not implemented

https://github.com/Unity-Technologies/com.unity.webrtc/blob/a39e89c2b18f37c093977ce3106f1305fd03992a/Runtime/Plugins/WebGL/Context.jslib#L213-L221

**Comment by nvanofwegen** [comment]
There is a WebGL scene in the Samples, which uses the UserMedia API of the browser.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/a39e89c2b18f37c093977ce3106f1305fd03992a/Samples~/WebGL/WebGLSample.cs#L104-L106

This basically create a VideoStream in Unity and attaches the MediaStream received from the UserMedia API on the javascript side. This stream is send to the receiver. 

Please note that this has little to nothing to do with the Audio implementation recently added in 2.4.0-exp.5:
- This branch is branched before the audio was implemented (pre exp.5)
- Audio is limited in WebGL, so it's not sure if it's compatible at all.

The methods you quoted (context register) were added to 'pass' the tests, but are not implemented.

Beside those limitations, you should be able to send your webcam/microphone using this package. It's just plain javascript functionality and cannot be used with Unity audio components.

Hope this helps :)

**Comment by Thaina** [comment]
I have been using this constraints to get the microphone

```C#
var receiveStream = new MediaStream();
receiveStream.AddUserMedia(new (){ audio = true,video = false });
```

And now I have hacked js like this

```js
  ContextRegisterAudioReceiveCallback: function (contextPtr, trackPtr, AudioTrackOnReceive){
    if (!uwcom_existsCheck(contextPtr, 'ContextRegisterAudioReceiveCallback', 'context')) return;
    if (!uwcom_existsCheck(trackPtr, 'ContextRegisterAudioReceiveCallback', 'track')) return;
    var ctx = UWManaged[contextPtr];
    /** @type {MediaStreamTrack} */
    var audioStreamTrack = UWManaged[trackPtr];

    const audioContext = new AudioContext();
    const microphone = audioContext.createMediaStreamSource(new window.MediaStream([audioStreamTrack]));
    const analyserNode = audioContext.createAnalyser();
    analyserNode.fftSize = 2048;
    microphone.connect( analyserNode );

    /** @type {Float32Array} */
    var dataArray = null;
    function live(){
      requestAnimationFrame(live);

      var bufferLength = analyserNode.frequencyBinCount;
      if(dataArray == null || dataArray.length != bufferLength)
        dataArray = new Float32Array(bufferLength);

      //Get spectrum data
      analyserNode.getFloatFrequencyData(dataArray);

      var refValue = 0.001;
      for (let i = 0; i < bufferLength; i++) {
        dataArray[i] = refValue * Math.pow(10,(dataArray[i] + 120) / 20); // convert decibel to 0-1 (?)
      }

      Module.dynCall_viii(AudioTrackOnReceive, trackPtr, dataArray, 0);
    }

    live();
  },
```

The callback `OnAudioReceive` was called and it now try to create clip from `float[]` but the `dataArray` are not marshalled properly (seem like I forgot to cast it to pointer?) But the loop seem reasonably possible to send and receive raw sound data into unity's `AudioClip`

**Comment by Thaina** [comment]
Currently now I have clone this repo and add these (and only these) code to `experimental/webgl-platform` branch

```js
  // Runtime\Plugins\WebGL\Context.jslib:213
  ContextRegisterAudioReceiveCallback: function (contextPtr, trackPtr, AudioTrackOnReceive){
    if (!uwcom_existsCheck(contextPtr, 'ContextRegisterAudioReceiveCallback', 'context')) return;
    if (!uwcom_existsCheck(trackPtr, 'ContextRegisterAudioReceiveCallback', 'track')) return;
    var ctx = UWManaged[contextPtr];
    /** @type {MediaStreamTrack} */
    var audioStreamTrack = UWManaged[trackPtr];

    const audioContext = new AudioContext();
    const microphone = audioContext.createMediaStreamSource(new window.MediaStream([audioStreamTrack]));
    const analyserNode = audioContext.createAnalyser();

    microphone.connect( analyserNode );

    var bufferLength = analyserNode.frequencyBinCount;
    var dataArray = new Float32Array(bufferLength);
    function live() {
      requestAnimationFrame(live);

      analyserNode.getFloatFrequencyData(dataArray);

      var settings = audioStreamTrack.getSettings();
      var ptr = uwcom_arrayToReturnPtr(dataArray, Float32Array);
      Module.dynCall_viiiiii(AudioTrackOnReceive, trackPtr, ptr + 4, bufferLength,settings.sampleRate , settings.channelCount, settings.sampleSize);
    }

    live();
  },
```

```C#
    // Runtime\Scripts\AudioStreamTrack.cs:257
        [AOT.MonoPInvokeCallback(typeof(DelegateAudioReceive))]
        static void OnAudioReceive(
            IntPtr ptrTrack, float[] audioData, int size, int sampleRate, int numOfChannels, int numOfFrames)
        {
            WebRTC.Sync(ptrTrack, () =>
            {
                if (WebRTC.Table[ptrTrack] is AudioStreamTrack track)
                {
                    foreach(var i in Enumerable.Range(0,audioData.Length))
                        audioData[i] = Mathf.Clamp01(Mathf.Pow(10,audioData[i] / 20));

                    track.OnAudioReceivedInternal(audioData, sampleRate, numOfChannels, numOfFrames);
                }
            });
        }
```

I now could send `audioData` which is an array of float in decibel from the microphone into unity. However now it still cannot create `AudioClip` properly and eventually throw these exception and stop the loop

<details>
  <summary>Invoking error handler due to
RuntimeError: null function or function signature mismatch
</summary>
  
```
Invoking error handler due to
RuntimeError: null function or function signature mismatch
at wasm://wasm/06cfd8fe:wasm-function[17810]:0x5ea515
    at wasm://wasm/06cfd8fe:wasm-function[34739]:0xc0a3af
    at wasm://wasm/06cfd8fe:wasm-function[74214]:0x15080ce
    at wasm://wasm/06cfd8fe:wasm-function[60521]:0x12a96c3
    at wasm://wasm/06cfd8fe:wasm-function[42938]:0xdf8063
    at invoke_vii (blob:https://192.168.1.128:55555/81b1912c-55c2-487c-98f9-9160405d93db:4542:444127)
    at wasm://wasm/06cfd8fe:wasm-function[74154]:0x1506237
    at wasm://wasm/06cfd8fe:wasm-function[55110]:0x11ceb11
    at wasm://wasm/06cfd8fe:wasm-function[10861]:0x364af9
    at wasm://wasm/06cfd8fe:wasm-function[42936]:0xdf804b
    at invoke_iiii (blob:https://192.168.1.128:55555/81b1912c-55c2-487c-98f9-9160405d93db:4542:442916)
    at wasm://wasm/06cfd8fe:wasm-function[2049]:0xad693
    at wasm://wasm/06cfd8fe:wasm-function[39934]:0xd4daa5
    at wasm://wasm/06cfd8fe:wasm-function[25154]:0x9d9ea4
    at wasm://wasm/06cfd8fe:wasm-function[10973]:0x368b37
    at wasm://wasm/06cfd8fe:wasm-function[15065]:0x546d83
    at wasm://wasm/06cfd8fe:wasm-function[1991]:0xab79e
    at wasm://wasm/06cfd8fe:wasm-function[19648]:0x668b85
    at wasm://wasm/06cfd8fe:wasm-function[20323]:0x69e9ca
    at wasm://wasm/06cfd8fe:wasm-function[3331]:0xfa9ed
    at wasm://wasm/06cfd8fe:wasm-function[42937]:0xdf8057
    at invoke_iii (blob:https://192.168.1.128:55555/81b1912c-55c2-487c-98f9-9160405d93db:4542:442748)
    at wasm://wasm/06cfd8fe:wasm-function[1764]:0xa1659
    at wasm://wasm/06cfd8fe:wasm-function[20557]:0x6c631c
    at wasm://wasm/06cfd8fe:wasm-function[636]:0x682f8
    at wasm://wasm/06cfd8fe:wasm-function[635]:0x682e2
    at wasm://wasm/06cfd8fe:wasm-function[34401]:0xc0136d
    at wasm://wasm/06cfd8fe:wasm-function[9310]:0x2c112a
    at wasm://wasm/06cfd8fe:wasm-function[34608]:0xc07a99
    at wasm://wasm/06cfd8fe:wasm-function[34609]:0xc07af0
    at wasm://wasm/06cfd8fe:wasm-function[74041]:0x1502ed3
    at wasm://wasm/06cfd8fe:wasm-function[42938]:0xdf8063
    at invoke_vii (blob:https://192.168.1.128:55555/81b1912c-55c2-487c-98f9-9160405d93db:4542:444127)
    at wasm://wasm/06cfd8fe:wasm-function[74042]:0x1502fbf
    at wasm://wasm/06cfd8fe:wasm-function[55110]:0x11ceb11
    at wasm://wasm/06cfd8fe:wasm-function[10861]:0x364af9
    at wasm://wasm/06cfd8fe:wasm-function[42936]:0xdf804b
    at invoke_iiii (blob:https://192.168.1.128:55555/81b1912c-55c2-487c-98f9-9160405d93db:4542:442916)
```
</details>

**Comment by Thaina** [comment]
Is this feature was deprecated?

**Comment by karasusan** [comment]
@Thaina
Sorry for waiting this but we haven't start to make it.

**Comment by Thaina** [comment]
@karasusan Are there anything blocking? I would like to have some prospect and vision of this feature so maybe I could start making pull request

**Comment by karasusan** [comment]
@Thaina
This branch is old and isn't following the latest update. But you can check the idea.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/experimental/webgl-platform

**Comment by Thaina** [comment]
I have already check that branch but it still stay at the same place

https://github.com/Unity-Technologies/com.unity.webrtc/blob/a39e89c2b18f37c093977ce3106f1305fd03992a/Runtime/Plugins/WebGL/Context.jslib#L213-L221

Should there be anything else I need to concern before start implement this?

**Comment by Thaina** [comment]
No, I am very sorry but that branch is not really work. I just fork to try to implement it but never finishing

**Comment by vertexfox** [comment]
> No, I am very sorry but that branch is not really work yet. I just fork to try to implement it but never finishing. Only finish the migration to newer version

Oh, okay. Thanks for letting me know 🫡

**Comment by wzxinchen1** [comment]
I want to install this branch to my project, does anyone can tell me how to do it?
thx
https://github.com/Unity-Technologies/com.unity.webrtc/tree/thaina/experimental/webgl-platform

**Comment by Thaina** [comment]
If you don't mind that the branch is not really finished implementation

with UPM you can

- Clone it, checkout any branch you want, and reference it as local package
- Reference it as git package with this link > https://github.com/Unity-Technologies/com.unity.webrtc.git#thaina/experimental/webgl-platform < the # is syntax to select branch or tag

**Comment by wzxinchen1** [comment]
> If you don't mind that the branch is not really finished implementation
> 
> with UPM you can
> 
> * Clone it, checkout any branch you want, and reference it as local package
> * Reference it as git package with this link > https://github.com/Unity-Technologies/com.unity.webrtc.git#thaina/experimental/webgl-platform < the # is syntax to select branch or tag

Thanks so much!
I want to use text communication only, this should be supported, right?
